#! /bin/bash

# Prometheus package management tool set
# Copyright (C) 2003-2004 Oliver Brakmann <oliverbrakmann@users.berlios.de> &
# Gareth Jones <gareth_jones@users.berlios.de>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

# Usage: runtest [!] <script> <message>
# Run <script>.  If script exits successfully, output:
#
#	Testing <message>...					Passed
#
# otherwise output:
#
#	<message>...
#	[<script> output]
#
#	<script>: <message> failed
#
# Return the exit value of script.  If `!' precedes <script>, reverse its exit
# status.  This is used for tests that are supposed to fail.

# Get parameters.
if [[ "$1" == "!" ]]; then
	should_fail=yes
	shift
fi

testscript="$1"
shift
message="$*"

echo "Testing $message..."

# Run the test.
if [[ "$should_fail" == yes ]]; then
	! "$testscript"
else
	"$testscript"
fi

declare -i retval=$?

if (( $retval == 0 )); then

	# Add passed to end of line.
	echo -e "\033[A\033[70GPassed"
else
	# Report failue to stderr.
	echo >&2
	echo "$testscript: $message failed" >&2
fi

exit $retval
