#! /bin/bash

# Prometheus package management tool set
# Copyright (C) 2003-2004 Oliver Brakmann <oliverbrakmann@users.berlios.de> &
# Gareth Jones <gareth_jones@users.berlios.de>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

# Usage: runtest [!] <script> <message>
# Set the current working directory to the directory containing <script>, & run
# <script>.  <script>'s stdout & stderr are redirected to a file in the same
# directory with the same basename as <script> & suffix `.log'.  The log is
# deleted if <script> exits successfully.  Return the exit value of script.  If
# `!' precedes <script>, reverse its exit status.  This is used for tests that
# are supposed to fail.

# Should we expect failure?
if [[ "$1" == "!" ]]; then
	should_fail=yes
	shift
fi

# Get script, directory & log.
script="${1##*/}"
directory="${1%$script}"
log="${script%bash}log"
shift

# Run script in its directory.
[[ -n "$directory" ]] && cd "$directory"

message="$*"
echo "Testing $message..."

# Run the test.
if [[ "$should_fail" == yes ]]; then
	! "./$script" &> "$log"
else
	"./$script" &> "$log"
fi

declare -i retval=$?

if (( $retval == 0 )); then

	# Remove log & add passed to end of line.
	rm "$log"
	echo -e "\033[A\033[70GPassed"
else
	# Report failue to stderr.
	echo "$directory$script: $message failed" >&2
	echo "see $directory$log for details" >&2
fi

exit $retval
